[project]
name = 'Criminal-Justice-Transformation-Lab'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.reentry-support-coordination]
path = 'contracts/reentry-support-coordination.clar'
clarity_version = 3
epoch = 'latest'

[contracts.restorative-justice-mediation]
path = 'contracts/restorative-justice-mediation.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
